wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      2:
      - 1
      - 5
      4: 3.7.9
      5: 0.10.31
      8:
      - 5
epochs:
  desc: null
  value: 2
fc_features:
  desc: null
  value: 128
filters:
  desc: null
  value: 32
image_dim:
  desc: null
  value: 28
kernel_size:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0001
n_classes:
  desc: null
  value: 10
